name: Flutter CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Analyze code
        run: flutter analyze
      
      - name: Run tests
        run: flutter test
      
      - name: Build APK
        run: flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  deploy-android:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy from main branch
    steps:
      - name: Download APK
        uses: actions/download-artifact@v3
        with:
          name: release-apk
      
      # Here you would add your preferred deployment method
      # For example, Firebase App Distribution:
      # - name: Deploy to Firebase App Distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{ secrets.FIREBASE_APP_ID }}
      #     serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
      #     groups: testers
      #     file: app-release.apk

  deploy-ios:
    needs: build
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main' # Only deploy from main branch
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      
      # For actual iOS deployment, you would need:
      # - Code signing setup
      # - TestFlight or App Store Connect deployment
      # This is commented out as it requires specific Apple Developer credentials
      # - name: Deploy to TestFlight
      #   uses: apple-actions/upload-testflight-build@v1
      #   with:
      #     app-path: build/ios/iphoneos/Runner.app
      #     apple-id: ${{ secrets.APPLE_ID }}
      #     password: ${{ secrets.APPLE_PASSWORD }}