name: Flutter CI - Build APK Only

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.4'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Check if APK exists
        run: |
          if [ -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
            echo "✅ APK built successfully."
          else
            echo "❌ APK not found!"
            exit 1
          fi

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
