name: Flutter Build Pipeline

on:
  push:
    branches: [ main, master ] # Trigger on pushes to main/master branches

jobs:
  build-and-release:
    name: Test, Build & Release APK
    runs-on: ubuntu-22.04 # Pinned to specific LTS version
    permissions:
      contents: write # Required for creating releases

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Eclipse Temurin distribution
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.13.0
        with:
          flutter-version: '3.22.2' # Latest stable Flutter version
          channel: 'stable'
          cache: true # Enable caching of Flutter dependencies
          cache-key: flutter-${{ runner.os }}-${{ matrix.flutter-version }}-${{ hashFiles('pubspec.lock') }}

      - name: Restore Pub Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            **/build
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

      - name: Build Profile APK
        run: flutter build apk --profile

      - name: Upload Release Asset
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "build/app/outputs/flutter-apk/app-profile.apk"
          tag: ${{ github.ref_name }}-${{ github.run_id }} # Unique tag for each run
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }} # Use built-in token (requires contents: write permission)