# To add CI/CD into git for Flutter:

# -  Create project and upload it to Git

# - Go to Action > Dart (configure) > find Flutter Action from Marketplace

# - Then Create main.yaml file and add below script:
on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --profile
      - name: Build profile APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-profile.apk"
          token: ${{ secrets.TOKEN }}
# - To get Token, go git project setting > Secrets and variables > Actions> Secrets > New repository secrets >
# add secret key name (here CICD) > and add secret key
